projects:
  tip:
    schemaPath: amplify/backend/api/tip/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/core/services/API.service.ts
        docsFilePath: src/graphql
        region: us-west-2
        apiId: null
        maxDepth: 3
extensions:
  amplify:
    version: 3
